nginx:
    image: nginx:alpine
    ports: 
        - "80:80"
    links: 
        - phpfpm
    volumes: 
        - ./nginx/default:/etc/nginx/sites-available/default
        - ./nginx/default:/etc/nginx/sites-enabled/default

        - ./logs/nginx-error.log:/var/lod/nginx/error.log
        - ./logs/nginx-access.log:/var/log/nginx/access.log

phpfpm:
    image: php:fpm
    ports:
        - "8000:8000"
    volumes: 
        - ./public:/usr/share/nginx/html

mydb:
    image: mariadb
    environment: 
        MYSQL_ROOT_PASSWORD: admin

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
        - mydb
    ports:
        - "8183:80"
    environment: 
        - PMA_ARBITRARY=1        